# Generated by Django 4.0.5 on 2022-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_validations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
